const data = {
  products: [
    {
      _id: "1",
      name: "Apple Airpods Pro",
      category: "headphones",
      image: "/images/p1.jpg",
      price: 200,
      countInStock: 5,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Apple Watch 6",
      category: "smartwatch",
      image: "/images/p2.jpg",
      price: 400,
      countInStock: 10,
      brand: "Apple",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Garmin Watch",
      category: "smartwatch",
      image: "/images/p3.jpg",
      price: 250,
      countInStock: 4,
      brand: "Garmin",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Huawei Honor Watch",
      category: "smartwatch",
      image: "/images/p4.jpg",
      price: 200,
      countInStock: 0,
      brand: "Huawei",
      rating: 3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Apple Iphone 12",
      category: "smartphone",
      image: "/images/p5.jpg",
      price: 700,
      countInStock: 16,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Apple Macbook Air",
      category: "computers",
      image: "/images/p6.jpg",
      price: 999,
      countInStock: 4,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
